d <- as.Date("2024/12/01")

format(d,"%B %d %y")
format(d,"%b %d %y")
format(d,"%B %d %Y")
format(d,"%m %d %y")
format(d,"%B %a %y")
format(d,"%B %A %y")
format(d,"%B %a %d %y")
format(d,"%Y /%d/ %m")
format(d,"%d /%Y /%m")